// Generated by gencpp from file common_msgs/objG.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_OBJG_H
#define COMMON_MSGS_MESSAGE_OBJG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_msgs
{
template <class ContainerAllocator>
struct objG_
{
  typedef objG_<ContainerAllocator> Type;

  objG_()
    : x()
    , y()
    , id()  {
    }
  objG_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_type;
  _x_type x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_type;
  _y_type y;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::common_msgs::objG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::objG_<ContainerAllocator> const> ConstPtr;

}; // struct objG_

typedef ::common_msgs::objG_<std::allocator<void> > objG;

typedef boost::shared_ptr< ::common_msgs::objG > objGPtr;
typedef boost::shared_ptr< ::common_msgs::objG const> objGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::objG_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::objG_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::objG_<ContainerAllocator1> & lhs, const ::common_msgs::objG_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::objG_<ContainerAllocator1> & lhs, const ::common_msgs::objG_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::objG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::objG_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::objG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::objG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::objG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::objG_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::objG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6188e5fbb63240cc314fffcd309fd006";
  }

  static const char* value(const ::common_msgs::objG_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6188e5fbb63240ccULL;
  static const uint64_t static_value2 = 0x314fffcd309fd006ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::objG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/objG";
  }

  static const char* value(const ::common_msgs::objG_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::objG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] x\n"
"float32[] y\n"
"int32[] id\n"
"\n"
;
  }

  static const char* value(const ::common_msgs::objG_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::objG_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objG_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::objG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::objG_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_OBJG_H
